name: Deploy to Server

on:
  push:
    branches:
      - dev3

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js 16
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Deploy to Server
      run: |
        const FtpDeploy = require('ftp-deploy');

        const config = {
          host: ${{ secrets.FTP_HOST }},
          username: ${{ secrets.FTP_USERNAME }},
          privateKey: ${{ secrets.SH_PRIVATE_KEY }},
          localRoot: './'
          
          // other configuration options...
        };

        const ftpDeploy = new FtpDeploy();

        ftpDeploy.deploy(config, (err) => {
          if (err) {
            console.error(err);
            process.exit(1);
          } else {
            console.log('Deployment finished successfully');
          }
        });
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
